[2024-06-24T16:04:29.365+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-24T16:04:29.477+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.task1 scheduled__2021-08-09T00:00:00+00:00 [queued]>
[2024-06-24T16:04:29.593+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.task1 scheduled__2021-08-09T00:00:00+00:00 [queued]>
[2024-06-24T16:04:29.603+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-24T16:04:29.959+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): task1> on 2021-08-09 00:00:00+00:00
[2024-06-24T16:04:30.027+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'task1', 'scheduled__2021-08-09T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpa6dkitlm']
[2024-06-24T16:04:30.025+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=279) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-24T16:04:30.075+0000] {standard_task_runner.py:63} INFO - Started process 291 to run task
[2024-06-24T16:04:30.073+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask task1
[2024-06-24T16:05:04.379+0000] {cli_action_loggers.py:137} WARNING - Failed to log action (MySQLdb.OperationalError) (2005, "Unknown server host 'mysql' (-3)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-06-24T16:05:05.438+0000] {task_command.py:426} INFO - Running <TaskInstance: first_dag.task1 scheduled__2021-08-09T00:00:00+00:00 [running]> on host 7608b9084855
[2024-06-24T16:05:05.973+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='tien' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2021-08-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-08-09T00:00:00+00:00'
[2024-06-24T16:05:05.996+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-24T16:05:07.084+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-24T16:05:07.097+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Hello World']
[2024-06-24T16:05:07.136+0000] {subprocess.py:86} INFO - Output:
[2024-06-24T16:05:07.330+0000] {subprocess.py:93} INFO - Hello World
[2024-06-24T16:05:07.341+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-06-24T16:05:07.356+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-24T16:05:07.677+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=task1, run_id=scheduled__2021-08-09T00:00:00+00:00, execution_date=20210809T000000, start_date=20240624T160429, end_date=20240624T160507
[2024-06-24T16:05:07.988+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-24T16:05:08.245+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-24T16:05:08.250+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
